Games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('show/', views.game_list, name='game-list'),
    path('show/<int:pk>/', views.game_detail, name='game-detail'),
    path('add/', views.game_create, name='game-create'),
    path('edit/<int:pk>/', views.game_edit, name='game-edit'),
    path('delete/<int:pk>/', views.game_delete, name='game-delete'),
    path('delete/<int:pk>/comment/<int:ck>/', views.comment_delete, name='comment-delete'),
    path('report/<int:pk>/comment/<int:ck>/', views.comment_report, name='comment-report'),
    path('approve/<int:pk>/comment/<int:ck>/', views.comment_approval, name='comment-approval'),
    path('show/<int:pk>/comment/<int:ck>/vote/<str:up_or_down>/', views.comment_vote, name='comment-vote'),
    path('search/', views.game_search, name='game-search'),
]

Settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('games/', include('Games.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('shoppingcart/', include('Shoppingcart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Games/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django.conf import settings
from django import template

register = template.Library()

class Game(models.Model):
    class GameGenre(models.TextChoices):
        EMPTY = '', _('Nothing selected')
        FIRSTPERSONSHOOTER = 'FPS', _('First Person Shooter')
        SIMULATION = 'SIM', _('Simulation')
        CITYBUILDER = 'CB', _('City Builder')
        HORRORGAME = 'HG', _('Horror Game')
        ROLEPLAYINGGAME = 'RPG', _('Role Playing Game')
        RACINGGAME = 'RC', _('Racing Game')

    class AgeRatings(models.TextChoices):
        EMPTY = '', _('Nothing selected')
        F00 = '0+', _('from 0')
        F06 = '6+', _('from 6')
        F12 = '12+', _('from 12')
        F16 = '16+', _('from 16')
        F18 = '18+', _('from 18')

    # Game title, description, creator and date that the game was released
    title = models.CharField(blank=False, max_length=100)
    description = models.TextField(blank=False)
    creator = models.CharField(blank=False, max_length=100)
    release_date = models.DateTimeField(blank=False, default=datetime.now)
    cover_image = models.ImageField(upload_to='images/games', default='')
    price = models.IntegerField(default=0, blank=False)
    product_data_pdf = models.FileField(upload_to='documents/games', default='')
    total_rating = models.DecimalField(default=0, decimal_places=1, max_digits=2, validators=[MinValueValidator(0), MaxValueValidator(5)])

    # Game genre and age rating
    genre = models.CharField(max_length=4, choices=GameGenre.choices, default=GameGenre.EMPTY)
    age_rating = models.CharField(max_length=4, choices=AgeRatings.choices, default=AgeRatings.EMPTY)

    # User who entered the game into the DB and when
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='users', related_query_name='user')
    upload_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title', 'genre']
        verbose_name = 'Game'
        verbose_name_plural = 'Games'
        get_latest_by = "release_date"

    def get_reported_comments_count(self):
        comments = Comment.objects.filter(approved=False, game=self)
        return len(comments)

    def __str__(self):
        return_string = self.title+', Creator: '+self.creator+', Released: '+self.release_date.strftime("%d.%m.%Y %H:%M:%S")+', Genre: '+self.genre+', Suitable for the ages '+self.age_rating+'; '+'Price:' + str(self.price)
        return return_string

    def __repr__(self):
        return_string = self.title+'/'+self.creator+'/'+self.release_date.strftime("%d.%m.%Y %H:%M:%S")+'/description('+str(len(self.description))+')/'+self.genre+'/'+self.age_rating+'/'+str(self.price)+'€'
        return return_string

class Comment(models.Model):
    text = models.TextField(max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    approved = models.BooleanField(default=True)
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])

    class Meta:
        ordering = ['timestamp']
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def get_comment_prefix(self):
        if len(self.text) > 50:
            return self.text[:50] + ' ...'
        else:
            return self.text

    def get_upvotes(self):
        upvotes = Vote.objects.filter(up_or_down='U', comment=self)
        return upvotes

    def get_upvotes_count(self):
        return len(self.get_upvotes())

    def get_downvotes(self):
        downvotes = Vote.objects.filter(up_or_down='D', comment=self)
        return downvotes

    def get_downvotes_count(self):
        return len(self.get_downvotes())

    def vote(self, user, up_or_down):
        U_or_D = 'U'
        if up_or_down == 'down':
            U_or_D = 'D'
        vote = Vote.objects.create(up_or_down=U_or_D, user=user, comment=self)

    def report(self):
        self.approved = False

    def approve(self):
        self.approved = True

    def __str__(self):
        return self.get_comment_prefix() + ' (' + self.user.username + ')'

    def __repr__(self):
        return self.get_comment_prefix() + ' (' + self.user.username + ' / ' + self.timestamp.strftime("%d.%m.%Y %H:%M:%S") + ')'

class Vote(models.Model):

    VOTE_TYPES = [
        ('U', 'up'),
        ('D', 'down'),
    ]

    def change_vote(self, new_vote):
        self.up_or_down = new_vote

    up_or_down = models.CharField(max_length=1, choices=VOTE_TYPES)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

Games/forms.py
from django import forms
from .models import Game, Comment

class GameForm(forms.ModelForm):

    class Meta:
        model = Game
        fields = ['title', 'description', 'cover_image', 'product_data_pdf', 'creator', 'release_date', 'genre', 'age_rating', 'price']
        widgets = {
            'genre': forms.Select(choices=Game.GameGenre),
            'age_rating': forms.Select(choices=Game.AgeRatings),
            'user': forms.HiddenInput(),
            'cover_image': forms.FileInput(attrs={
                'accept': '.jpg, .jpeg, .png'}
            ),
            'product_data_pdf': forms.FileInput(attrs={
                'accept': '.pdf'}
            ),
        }

class GameEditForm(forms.ModelForm):

    cover_image = forms.ImageField(required=False)
    product_data_pdf = forms.FileField(required=False)
    class Meta:
        model = Game
        fields = ['title', 'description', 'cover_image', 'product_data_pdf', 'creator', 'release_date', 'genre', 'age_rating', 'price']
        widgets = {
            'genre': forms.Select(choices=Game.GameGenre),
            'age_rating': forms.Select(choices=Game.AgeRatings),
            'user': forms.HiddenInput(),
            'cover_image': forms.FileInput(attrs={
                'accept': '.jpg, .jpeg, .png'}
            ),
            'product_data_pdf': forms.FileInput(attrs={
                'accept': '.pdf'}
            ),
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['rating', 'text']
        widgets = {
            'user': forms.HiddenInput(),
            'game': forms.HiddenInput(),
        }
class SearchForm(forms.ModelForm):

    creator = forms.CharField(required=False)
    title = forms.CharField(required=False)
    genre = forms.ChoiceField(choices=Game.GameGenre.choices, required=False)
    age_rating = forms.ChoiceField(choices=Game.AgeRatings.choices, required=False)

    class Meta:
        model = Game
        fields = ['creator', 'title', 'genre', 'age_rating', 'total_rating']

Games/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from Shoppingcart.models import ShoppingCart
from .forms import GameForm, GameEditForm, CommentForm, SearchForm
from .models import Game, Comment, Vote

def game_list(request):
    all_games = Game.objects.all()
    context = {'all_the_games': all_games}
    return render(request, 'game-list.html', context)

def game_detail(request, **kwargs):
    game_id = kwargs['pk']
    game = Game.objects.get(id=game_id)
    comments = Comment.objects.filter(game=game)

    context = {
        'that_one_game': game,
        'comments_for_that_one_game': comments,
        'comment_form': CommentForm,
    }

    if request.method == 'POST':
        if request.POST['action'] == 'comment':
            form = CommentForm(request.POST)
            form.instance.user = request.user
            form.instance.game = game
            if form.is_valid():
                form.save()
                return redirect('game-detail', pk=game_id)
            else:
                print(form.errors)
        elif request.POST['action'] == 'add-to-cart':
            ShoppingCart.add_item(request.user, game)

    return render(request, 'game-detail.html', context)

@staff_member_required
def game_create(request):
    form = GameForm()
    context = {'form': form}
    if request.method == 'POST':
        form = GameForm(request.POST, request.FILES)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('game-list')
        else:
            print(form.errors)

    return render(request, 'game-create.html', context)

@staff_member_required
def game_edit(request, **kwargs):
    game_id = kwargs['pk']
    game = Game.objects.get(id=game_id)

    form = GameEditForm()
    context = {
        'form': form,
        'that_one_game': game
    }

    if request.method == 'POST':
        form = GameEditForm(request.POST or None, request.FILES, instance=game)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('game-detail', pk=game_id)
        else:
            print(form.errors)

    return render(request, 'game-edit.html', context)

@staff_member_required
def game_delete(request, **kwargs):
    game_id = kwargs['pk']
    that_one_game = Game.objects.get(id=game_id)
    if request.method == 'POST':
        that_one_game.delete()
        return redirect('game-list')
    else:
        context = {'that_one_game': that_one_game}
        return render(request, 'game-delete.html', context)

@login_required()
def comment_delete(request, **kwargs):
    comment_id = kwargs['ck']
    game_id = kwargs['pk']
    comment = Comment.objects.get(id=comment_id)
    if request.user.username == comment.user.username or request.user.is_staff:
        comment.delete()
        return redirect('game-detail', pk=game_id)

@login_required()
def comment_report(request, **kwargs):
    comment_id = kwargs['ck']
    game_id = kwargs['pk']
    comment = Comment.objects.get(id=comment_id)
    comment.report()
    comment.save()
    return redirect('game-detail', pk=game_id)

@staff_member_required
def comment_approval(request, **kwargs):
    comment_id = kwargs['ck']
    game_id = kwargs['pk']
    comment = Comment.objects.get(id=comment_id)
    comment.approve()
    comment.save()
    return redirect('game-detail', pk=game_id)

@login_required()
def comment_vote(request, pk: str, ck: int, up_or_down: str):
    comment_id = int(ck)
    comment = Comment.objects.get(id=comment_id)
    user = request.user

    if Vote.objects.filter(comment=comment_id, user=request.user).exists():
        existing_vote = Vote.objects.get(comment=comment_id, user=request.user)
        if up_or_down == 'up':
            if existing_vote.up_or_down == 'U':
                existing_vote.delete()
            elif existing_vote.up_or_down == 'D':
                existing_vote.change_vote('U')
                existing_vote.save()
        elif up_or_down == 'down':
            if existing_vote.up_or_down == 'U':
                existing_vote.change_vote('D')
                existing_vote.save()
            elif existing_vote.up_or_down == 'D':
                existing_vote.delete()
    else:
        comment.vote(user, up_or_down)

    return redirect('game-detail', pk=pk)


def game_search(request):
    if request.method == 'POST':

        games_found = Game.objects.filter(
            creator__contains=request.POST['creator'],
            title__contains=request.POST['title'],
            genre__contains=request.POST['genre'],
            age_rating__contains=request.POST['age_rating'],
            total_rating__gte=request.POST['total_rating']
        )

        if not games_found:
            show_results = False
        else:
            show_results = True
        form_in_function_based_view = SearchForm()
        context = {
            'form': form_in_function_based_view,
            'game_found': games_found,
            'show_results': show_results
        }
        return render(request, 'game-search.html', context)

    else:
        form_in_function_based_view = SearchForm()
        context = {'form': form_in_function_based_view,
                   'show_results': False}
        return render(request, 'game-search.html', context)

Games/templates/game-create.html
{% extends "home.html" %}

{% block title %}
    Add Game
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Games/css/game_styles.css' %}">
{% endblock %}

{% block heading %}
    <h1>Add Game</h1>
{% endblock %}

{% block logged_in_content %}
    <div class="game-create-content">
        <h2>Please fill out the fields.</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="{{ form.title.id_for_label }}">Title of the game</label><br>
            <input id="{{ form.title.id_for_label }}" type="{{ form.title.field.widget.input_type }}" name="{{ form.title.html_name }}" placeholder="Game title"><br>

            <label for="{{ form.cover_image.id_for_label }}">Cover image</label><br>
            {{ form.cover_image }}<br>

            <label for="{{ form.product_data_pdf.id_for_label }}">Product data PDF</label><br>
            {{ form.product_data_pdf }}<br>

            <label for="{{ form.creator.id_for_label }}">Developer/Game Studio</label><br>
            <input id="{{ form.creator.id_for_label }}" type="{{ form.creator.field.widget.input_type }}" name="{{ form.creator.html_name }}" placeholder="Developer/Game Studio"><br>

            <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label><br>
            {{ form.description }}<br>

            <label for="id_genre">Genre of the game</label><br>
            <select id="id_genre" type="text" name="genre">
                <option value="">---</option>
                <option value="FPS">First Person Shooter</option>
                <option value="SIM">Simulation</option>
                <option value="CB">City Builder</option>
                <option value="HG">Horror Game</option>
                <option value="RPG">Role Playing Game</option>
                <option value="RC">Racing Game</option>
            </select><br>

            <label for="{{ form.age_rating.id_for_label }}">{{ form.age_rating.label }}</label><br>
            {{ form.age_rating }}<br>

            <label for="{{ form.releas_date.id_for_label }}">{{ form.release_date.label }}</label><br>
            {{ form.release_date }}<br>

            <label for="{{ form.price.id_for_label }}">{{ form.price.label }}</label><br>
            {{ form.price }}<br>

            <div class="button-container">
                <button class="button primary" type="submit">Add Game</button>
                <a class="button secondary" href="{% url 'game-list' %}">Back to all games</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block not_logged_in_content %}
    <h2>You must be logged in to add games.</h2>
    <div class="button-container">
        <a class="button primary" hhref="{% url 'login' %}">Login</a>
        <a class="button secondary" hhref="{% url 'home' %}">Back to Home</a>
    </div>
{% endblock %}

Games/templates/game-detail.html
{% extends "home.html" %}

{% block title %}
    {{ that_one_game.title }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Games/css/game_styles.css' %}">
{% endblock %}

{% block heading %}
    <h1>{{ that_one_game.title }}</h1>
{% endblock %}

{% block logged_in_content %}
    <div class="game-detail-content">
        <div class="left-column">
            <h2>Game Information:</h2>
            {% load define_tags %}
            {% get_total_rating that_one_game as total_rating %}
            {% if total_rating == 99.9 %}
                <h3>Rating: No ratings yet.</h3>
            {% else %}
                <h3>Rating: {{ total_rating }} / 5</h3>
            {% endif %}
            <img width="300" src="{% if that_one_game.cover_image %}{{ that_one_game.cover_image.url }}{% endif %}">
            <ul>
                <li>Release date: {{ that_one_game.release_date }}</li>
                <li>Game Creator: {{ that_one_game.creator }}</li>
                <li>Genre: {{ that_one_game.get_genre_display }}</li>
                <li>Age rating: {{ that_one_game.age_rating }}</li>
            </ul>
            <h4>Description:</h4>
            <p class="game-detail-description">{{ that_one_game.description }}</p>
            <p class="game-detail-upload-date">Uploaded by: <i>{{ that_one_game.user }}</i> at <i>{{ that_one_game.upload_date }}</i></p>

            <h4>Price: </h4>
            <p class="price">{{ that_one_game.price }} €</p>

            {% if request.user.is_staff %}
                <p class="button-delete-container">
                    <a class="button primary button-delete" href="{% url 'game-delete' that_one_game.id %}">Delete Game</a>
                </p>
                <p class="button-edit-container">
                    <a class="button primary button-edit" href="{% url 'game-edit' that_one_game.id %}">Edit Game</a>
                </p>
            {% endif %}
            {% if that_one_game.product_data_pdf %}
                <div class="button-download-container">
                    <a class="button primary button-download" target="_blank" href="{{ that_one_game.product_data_pdf.url }}">Download PDF</a>
                </div>
            {% endif %}
            <div class="add-to-cart-container">
                <form method="POST">
                    {% csrf_token %}
                    <button class="button primary" type="submit" name="action" value="add-to-cart">Add to shopping cart</button>
                </form>
            </div>
            <div class="button-container">
                <a class="button secondary button-back" href="{% url 'game-list' %}">Back to all games</a>
                <a class="button secondary button-back-list" href="{% url 'home' %}">Back to Home</a>
            </div>
        </div>
        <div class="right-column">
            <h4 class="comments-heading">Reviews:</h4>
            <div class="comments-container">
                {% if not comments_for_that_one_game %}
                    <p>No reviews yet. Be the first to review!</p>
                {% else %}
                    <ul class="comments-list">
                        {% for comment in comments_for_that_one_game %}
                                <li class="comment-list-element">
                                    <div>
                                        <p>{% if user.username == comment.user.username %}Your rating: {% else %}Rating: {% endif %}<strong>{{ comment.rating }}</strong></p>
                                        {% if comment.approved or user.is_staff %}
                                            <p class="comment-text">{{ comment.text }}</p>
                                        {% else %}
                                            <p>This comment has been reported and is waiting for approval.</p>
                                        {% endif %}
                                        <p class="comment-meta">By <i>{{ comment.user.username }}</i> on <i>{{ comment.timestamp }}</i>
                                            {% if user.username == comment.user.username or user.is_staff %}
                                                <a class="delete-link" href="{% url 'comment-delete' that_one_game.id comment.id %}">Delete review</a>
                                            {% endif %}
                                            {% if comment.approved and not user.is_staff and not user.username == comment.user.username%}
                                                <a class="report-link" href="{% url 'comment-report' that_one_game.id comment.id %}">Report review</a>
                                            {% endif %}
                                            {% if not comment.approved and user.is_staff %}
                                                <a class="approval-link" href="{% url 'comment-approval' that_one_game.id comment.id %}">Approve review</a>
                                            {% endif %}
                                        </p>
                                        <div class="comment-votes">
                                              <span style="color:darkgreen">
                                                  {{ comment.get_upvotes_count }}
                                                  <a href="{% url 'comment-vote' that_one_game.id comment.id 'up' %}" {% if request.user.is_staff %}class="disabled"{% endif %}>up</a>
                                              </span>
                                              <span style="color:crimson">
                                                  {{ comment.get_downvotes_count }}
                                                  <a href="{% url 'comment-vote' that_one_game.id comment.id 'down' %}" {% if request.user.is_staff %}class="disabled"{% endif %}>down</a>
                                              </span>
                                        </div>
                                    </div>
                                </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% load define_tags %}
                {% has_user_reviewed that_one_game user as has_user_reviewed%}
                {% if not request.user.is_staff and has_user_reviewed == False %}
                    <b>Do you want to leave a review?</b><br><br><br>
                    <form method="POST">
                        {% csrf_token %}
                        <label for="{{ comment_form.rating.id_for_label }}"><strong>Your rating (1-5):</strong></label><br><br>
                        <input id="{{ comment_form.rating.id_for_label }}" type="number" name="{{ comment_form.rating.html_name }}" min="1" max="5" placeholder="1"><br>
                        <br>
                        <label for="{{ comment_form.text.id_for_label }}"><strong>Your thoughts:</strong></label>
                        <textarea rows="10" cols="40" id="{{ comment_form.text.id_for_label }}" type="{{ comment_form.text.field.widget.input_type }}" name="{{ comment_form.text.html_name }}" placeholder="Write your review here..."></textarea><br><br>
                        <button class="button primary button-submit-comment" type="submit" name="action" value="comment">Add review</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block not_logged_in_content %}
    <h2>You must be logged in to view this game.</h2>
    <div class="button-container">
        <a class="button primary" hhref="{% url 'login' %}">Login</a>
        <a class="button secondary" hhref="{% url 'home' %}">Back to Home</a>
    </div>
{% endblock %}

Games/templates/game-edit.html
{% extends "home.html" %}

{% block title %}
    Edit Game
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Games/css/game_styles.css' %}">
{% endblock %}

{% block heading %}
    <h1>Edit Game</h1>
{% endblock %}

{% block logged_in_content %}
    <div class="game-create-content">
        <h2>Please fill out the fields.</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="{{ form.title.id_for_label }}">Title of the game</label><br>
            <input id="{{ form.title.id_for_label }}" type="{{ form.title.field.widget.input_type }}" name="{{ form.title.html_name }}" placeholder="Game title" value="{{ that_one_game.title }}"><br>

            <label for="{{ form.cover_image.id_for_label }}">Cover image</label><br>
            {{ form.cover_image }}<br>

            <label for="{{ form.product_data_pdf.id_for_label }}">Product data PDF</label><br>
            {{ form.product_data_pdf }}<br>

            <label for="{{ form.creator.id_for_label }}">Developer/Game Studio</label><br>
            <input id="{{ form.creator.id_for_label }}" type="{{ form.creator.field.widget.input_type }}" name="{{ form.creator.html_name }}" placeholder="Developer/Game Studio" value="{{ that_one_game.creator }}"><br>

            <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label><br>
            <textarea rows="10" cols="40" id="{{ form.description.id_for_label }}" type="{{ form.description.field.widget.input_type }}" name="{{ form.description.html_name }}" value="{{ that_one_game.description }}">{{ that_one_game.description }}</textarea><br>
            <br>

            <label for="id_genre">Genre of the game</label><br>
            <select id="id_genre" type="text" name="genre">
                <option value="">---</option>
                <option value="FPS" {% if that_one_game.genre == "FPS" %}selected{% endif %}>First Person Shooter</option>
                <option value="SIM" {% if that_one_game.genre == "SIM" %}selected{% endif %}>Simulation</option>
                <option value="CB" {% if that_one_game.genre == "CB" %}selected{% endif %}>City Builder</option>
                <option value="HG" {% if that_one_game.genre == "HG" %}selected{% endif %}>Horror Game</option>
                <option value="RPG" {% if that_one_game.genre == "RPG" %}selected{% endif %}>Role Playing Game</option>
                <option value="RC" {% if that_one_game.genre == "RC" %}selected{% endif %}>Racing Game</option>
            </select><br>

            <label for="{{ form.age_rating.id_for_label }}">{{ form.age_rating.label }}</label><br>
            <select id="{{ form.age_rating.id_for_label }}" type="{{ form.age_rating.field.widget.input_type }}" name="{{ form.age_rating.html_name }}">
                <option value="0+" {% if that_one_game.age_rating == "0+" %}selected{% endif %}>from 0</option>
                <option value="6+" {% if that_one_game.age_rating == "6+" %}selected{% endif %}>from 6</option>
                <option value="12+" {% if that_one_game.age_rating == "12+" %}selected{% endif %}>from 12</option>
                <option value="16+" {% if that_one_game.age_rating == "16+" %}selected{% endif %}>from 16</option>
                <option value="18+" {% if that_one_game.age_rating == "18+" %}selected{% endif %}>from 18</option>
            </select>
            <br>

            <label for="{{ form.release_date.id_for_label }}">{{ form.release_date.label }}</label><br>
            <input type="{{ form.release_date.field.widget.input_type }}" name="{{ form.release_date.html_name }}" value="{{ form.release_date.value|date:"Y-m-d h:m:s" }}" id="{{ form.release_date.id_for_label }}">
            <br>

            <label for="{{ form.price.id_for_label }}">Price</label><br>
            <input id="{{ form.price.id_for_label }}" type="{{ form.price.field.widget.input_type }}" name="{{ form.price.html_name }}" placeholder="Price" value="{{ that_one_game.price }}">
            <br>

            <div class="button-container">
                <button class="button primary" type="submit">Save Game</button>
                <a class="button secondary" href="{% url 'game-detail' that_one_game.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block not_logged_in_content %}
    <h2>You must be logged in to add games.</h2>
    <div class="button-container">
        <a class="button primary" hhref="{% url 'login' %}">Login</a>
        <a class="button secondary" hhref="{% url 'home' %}">Back to Home</a>
    </div>
{% endblock %}

Games/templates/game-list.html
{% extends "home.html" %}

{% block title %}
    All Games
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Games/css/game_styles.css' %}">
{% endblock %}

{% block heading %}
    <h1>All Games</h1>
{% endblock %}

{% block logged_in_content %}
    <div class="games-container">
        {% for game in all_the_games %}
            <div class="game-card">
                <h3>{{ game.title }}</h3>
                <p>Rating: {{ game.total_rating }}</p><br>
                <img class="game-list-cover" src="{% if game.cover_image %}{{ game.cover_image.url }}{% endif %}">
                <ul>
                    <li>Release date: {{ game.release_date }}</li>
                    <li>Game Creator: {{ game.creator }}</li>
                    <li>Genre: {{ game.get_genre_display }}</li>
                    <li>Age rating: {{ game.age_rating }}</li>
                </ul>
                <h4>Description:</h4>
                <p class="game-card-description">{{ game.description }}</p>
                <h4>Price: </h4><span class="price">{{ game.price }} €</span>
                <p>
                    <a class="button primary" href="{% url 'game-detail' game.id %}">View Details</a>
                </p>
                {% if user.is_staff and game.get_reported_comments_count > 0 %}
                    <p style="color:red;margin-top:30px;">Comments waiting for approval: {{ game.get_reported_comments_count }}</p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <div class="button-container">
        {% if request.user.is_staff %}
            <a class="button primary" href="{% url 'game-create' %}">Add a new game</a>
        {% endif %}
    </div>
{% endblock %}

{% block not_logged_in_content %}
    <h2>You must be logged in to view games.</h2>
    <div class="button-container">
        <a class="button primary" href="{% url 'login' %}">Login</a>
        <a class="button secondary" href="{% url 'home' %}">Back to Home</a>
    </div>
{% endblock %}